import { notFound } from "next/navigation";
import type { Metadata } from "next";
import Link from "next/link";
import { createClient } from "@/lib/supabase/server";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import type { Report } from "@/lib/supabase/types";
import { SharedReportContent } from "@/components/SharedReportContent";
import { SocialShareButtons } from "@/components/SocialShareButtons";

async function getReport(token: string): Promise<Report | null> {
  const supabase = await createClient();
  const { data, error } = await supabase
    .from("reports")
    .select("*")
    .eq("share_token", token)
    .eq("is_public", true)
    .single();

  if (error || !data) return null;
  return data as Report;
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ token: string }>;
}): Promise<Metadata> {
  const { token } = await params;
  const report = await getReport(token);

  if (!report) {
    return { title: "Report Not Found" };
  }

  const title = `DNA Analysis: ${report.trait} | DNA Trait Analyzer`;
  const description = report.summary.slice(0, 160);

  return {
    title,
    description,
    openGraph: {
      title,
      description,
      type: "article",
      siteName: "DNA Trait Analyzer",
    },
    twitter: {
      card: "summary",
      title,
      description,
    },
  };
}

export default async function SharedReportPage({
  params,
}: {
  params: Promise<{ token: string }>;
}) {
  const { token } = await params;
  const report = await getReport(token);

  if (!report) {
    notFound();
  }

  return (
    <div className="max-w-3xl mx-auto p-6 py-8 space-y-6">
      <div className="text-center space-y-2">
        <p className="text-sm text-muted-foreground">Shared DNA Report</p>
      </div>

      <Card>
        <CardHeader>
          <CardTitle className="capitalize">{report.trait}</CardTitle>
          <p className="text-sm text-muted-foreground">{report.summary}</p>
        </CardHeader>
        <CardContent className="space-y-6">
          <SharedReportContent report={report} />

          {report.sources.length > 0 && (
            <div>
              <h3 className="font-semibold mb-2">Research Sources</h3>
              <ul className="text-sm text-muted-foreground space-y-1">
                {report.sources.map((source: string, i: number) => (
                  <li key={i} className="flex items-start gap-2">
                    <span className="text-muted-foreground/50 select-none">
                      &bull;
                    </span>
                    {source}
                  </li>
                ))}
              </ul>
            </div>
          )}

          <Alert>
            <AlertDescription className="text-xs">
              {report.disclaimer}
            </AlertDescription>
          </Alert>

          <div className="text-center text-xs text-muted-foreground border-t pt-4">
            Generated by DNA Trait Analyzer on{" "}
            {new Date(report.created_at).toLocaleDateString()}
          </div>
        </CardContent>
      </Card>

      {/* Social sharing */}
      <div className="flex justify-center">
        <SocialShareButtons trait={report.trait} />
      </div>

      {/* CTA */}
      <Card className="text-center">
        <CardContent className="py-8 space-y-3">
          <h3 className="font-semibold text-lg">
            Curious about your own genetics?
          </h3>
          <p className="text-sm text-muted-foreground">
            Upload your DNA data and get AI-powered trait analysis backed by
            published research.
          </p>
          <Link href="/">
            <Button size="lg">Analyze Your DNA</Button>
          </Link>
        </CardContent>
      </Card>
    </div>
  );
}
