import { notFound } from "next/navigation";
import type { Metadata } from "next";
import Link from "next/link";
import { createClient } from "@/lib/supabase/server";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import type { Report } from "@/lib/supabase/types";
import { SharedReportContent } from "@/components/SharedReportContent";
import { SocialShareButtons } from "@/components/SocialShareButtons";
import { Share2, EyeOff } from "lucide-react";

async function getReport(token: string): Promise<Report | null> {
  const supabase = await createClient();
  const { data, error } = await supabase
    .from("reports")
    .select("*")
    .eq("share_token", token)
    .eq("is_public", true)
    .single();

  if (error || !data) return null;
  return data as Report;
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ token: string }>;
}): Promise<Metadata> {
  const { token } = await params;
  const report = await getReport(token);

  if (!report) {
    return { title: "Report Not Found" };
  }

  const title = `DNA Analysis: ${report.trait} | DNA Trait Analyzer`;
  const description = report.summary.slice(0, 160);

  return {
    title,
    description,
    openGraph: {
      title,
      description,
      type: "article",
      siteName: "DNA Trait Analyzer",
    },
    twitter: {
      card: "summary",
      title,
      description,
    },
  };
}

export default async function SharedReportPage({
  params,
}: {
  params: Promise<{ token: string }>;
}) {
  const { token } = await params;
  const report = await getReport(token);

  if (!report) {
    notFound();
  }

  return (
    <div className="max-w-3xl mx-auto p-6 py-8 space-y-6">
      {/* Header with badge and brand */}
      <div className="text-center space-y-3">
        <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-primary/10 text-primary text-sm font-medium">
          <Share2 className="h-3.5 w-3.5" />
          Shared Report
        </div>
        <p className="font-display text-lg font-semibold text-muted-foreground">
          DNA Trait Analyzer
        </p>
      </div>

      <Card>
        <CardHeader>
          <CardTitle className="font-display capitalize text-2xl">{report.trait}</CardTitle>
          <p className="text-sm text-muted-foreground">{report.summary}</p>
        </CardHeader>
        <CardContent className="space-y-6">
          <SharedReportContent report={report} />

          {report.sources.length > 0 && (
            <div>
              <h3 className="font-semibold mb-2">Research Sources</h3>
              <ul className="text-sm text-muted-foreground space-y-1">
                {report.sources.map((source: string, i: number) => (
                  <li key={i} className="flex items-start gap-2">
                    <span className="text-muted-foreground/50 select-none">
                      &bull;
                    </span>
                    {source}
                  </li>
                ))}
              </ul>
            </div>
          )}

          <Alert>
            <AlertDescription className="text-xs">
              {report.disclaimer}
            </AlertDescription>
          </Alert>

          {/* Privacy note */}
          <div className="flex items-center gap-2 text-xs text-muted-foreground border-t pt-4">
            <EyeOff className="h-3.5 w-3.5 shrink-0" />
            <span>Raw genotype data hidden for privacy</span>
          </div>

          <div className="text-center text-xs text-muted-foreground">
            Generated by DNA Trait Analyzer on{" "}
            {new Date(report.created_at).toLocaleDateString()}
          </div>
        </CardContent>
      </Card>

      {/* Social sharing */}
      <div className="flex justify-center">
        <SocialShareButtons trait={report.trait} />
      </div>

      {/* CTA with gradient mesh bg */}
      <div className="relative rounded-xl overflow-hidden">
        <div className="absolute inset-0 bg-surface-elevated">
          <div className="absolute top-0 left-1/4 w-64 h-64 rounded-full bg-primary/10 blur-3xl" />
          <div className="absolute bottom-0 right-1/4 w-48 h-48 rounded-full bg-primary/5 blur-3xl" />
        </div>
        <div className="relative text-center py-12 px-6 space-y-4">
          <h3 className="font-display font-semibold text-xl">
            Discover your own genetic traits
          </h3>
          <p className="text-sm text-muted-foreground max-w-md mx-auto">
            Upload your DNA data and get AI-powered trait analysis backed by
            published research.
          </p>
          <Link href="/">
            <Button
              size="lg"
              className="bg-primary hover:bg-primary/90 hover:shadow-[0_0_20px_var(--glow-primary)] transition-all"
            >
              Analyze Your DNA
            </Button>
          </Link>
        </div>
      </div>
    </div>
  );
}
