import Link from "next/link";

export const metadata = {
  title: "Terms of Service - DNA Trait Analyzer",
  description: "Terms of Service for the DNA Trait Analyzer application.",
};

export default function TermsOfServicePage() {
  return (
    <div className="min-h-screen bg-background">
      <div className="max-w-3xl mx-auto px-6 py-16">
        <Link
          href="/"
          className="text-sm text-muted-foreground hover:text-foreground transition-colors"
        >
          &larr; Back to DNA Trait Analyzer
        </Link>

        <div className="mt-8 space-y-8">
          <div>
            <h1 className="font-display text-3xl font-bold tracking-tight">
              Terms of Service
            </h1>
            <p className="text-sm text-muted-foreground mt-2">
              Last updated: March 18, 2026
            </p>
            <div className="mt-4 rounded-lg border border-amber-500/30 bg-amber-500/10 px-4 py-3">
              <p className="text-sm text-amber-600 dark:text-amber-400 font-medium">
                TEMPLATE — This document requires review by a qualified attorney
                before use.
              </p>
            </div>
          </div>

          <section className="space-y-4">
            <h2 className="font-display text-xl font-semibold">1. Acceptance of Terms</h2>
            <p className="text-sm text-muted-foreground leading-loose">
              By accessing or using the DNA Trait Analyzer service
              (&quot;Service&quot;) operated by [COMPANY NAME]
              (&quot;Company,&quot; &quot;we,&quot; &quot;us,&quot; or
              &quot;our&quot;), you agree to be bound by these Terms of Service
              (&quot;Terms&quot;). If you do not agree to these Terms, you must
              not use the Service.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="font-display text-xl font-semibold">
              2. Educational Purpose Only — Not Medical Advice
            </h2>
            <p className="text-sm text-muted-foreground leading-loose">
              The Service is provided strictly for{" "}
              <strong>educational and informational purposes only</strong>. The
              Service does not provide medical advice, diagnoses, or treatment
              recommendations. Analysis results generated by the Service:
            </p>
            <ul className="list-disc list-inside text-sm text-muted-foreground space-y-1 ml-4 leading-loose">
              <li>
                Are not a substitute for professional medical advice, diagnosis,
                or treatment
              </li>
              <li>
                Should not be used to make health-related decisions without
                consulting a qualified healthcare professional
              </li>
              <li>
                Are based on publicly available research that may be incomplete,
                outdated, or not applicable to your specific circumstances
              </li>
              <li>
                Do not account for the full complexity of gene-gene
                interactions, epigenetics, or environmental factors
              </li>
            </ul>
            <p className="text-sm text-muted-foreground leading-loose font-medium">
              Always seek the advice of a qualified physician or genetic
              counselor with any questions regarding a medical condition or
              genetic testing.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="font-display text-xl font-semibold">
              3. AI-Generated Content Disclaimer
            </h2>
            <p className="text-sm text-muted-foreground leading-loose">
              The Service uses artificial intelligence (including Anthropic
              Claude) to generate trait analyses and interpretations. AI-generated
              content may contain errors, inaccuracies, or misinterpretations of
              scientific literature. You acknowledge that:
            </p>
            <ul className="list-disc list-inside text-sm text-muted-foreground space-y-1 ml-4 leading-loose">
              <li>
                AI outputs are probabilistic and not deterministic — results may
                vary
              </li>
              <li>
                The AI may &quot;hallucinate&quot; or fabricate citations,
                statistics, or associations
              </li>
              <li>
                Genetic research is a rapidly evolving field and AI training data
                may not reflect the latest findings
              </li>
              <li>
                You are responsible for independently verifying any information
                provided by the Service
              </li>
            </ul>
          </section>

          <section className="space-y-4">
            <h2 className="font-display text-xl font-semibold">
              4. User Responsibilities
            </h2>
            <p className="text-sm text-muted-foreground leading-loose">
              By using the Service, you represent and warrant that:
            </p>
            <ul className="list-disc list-inside text-sm text-muted-foreground space-y-1 ml-4 leading-loose">
              <li>
                You are at least 18 years of age or have the consent of a parent
                or legal guardian
              </li>
              <li>
                You are uploading <strong>only your own</strong> genetic data,
                or data for which you have explicit authorization to analyze
              </li>
              <li>
                You will not upload genetic data belonging to another person
                without their informed, written consent
              </li>
              <li>
                You will not use the Service for any unlawful purpose, including
                but not limited to genetic discrimination
              </li>
              <li>
                You will not attempt to reverse-engineer, de-anonymize, or
                re-identify any individual from genetic data
              </li>
            </ul>
          </section>

          <section className="space-y-4">
            <h2 className="font-display text-xl font-semibold">
              5. Data Handling and Retention
            </h2>
            <p className="text-sm text-muted-foreground leading-loose">
              We take the security and privacy of your genetic data seriously:
            </p>
            <ul className="list-disc list-inside text-sm text-muted-foreground space-y-1 ml-4 leading-loose">
              <li>
                Raw DNA files are processed server-side and are{" "}
                <strong>not permanently stored</strong> in their original form
              </li>
              <li>
                Only specific SNP identifiers relevant to your requested
                analysis are extracted and used
              </li>
              <li>
                Temporary session data (including extracted SNPs) is
                automatically deleted after 1 hour
              </li>
              <li>
                If you create an account, analysis reports may be stored as
                described in our{" "}
                <Link
                  href="/legal/privacy"
                  className="text-primary underline underline-offset-2 hover:text-primary/80"
                >
                  Privacy Policy
                </Link>
              </li>
              <li>
                You may request deletion of all your data at any time by
                contacting [CONTACT EMAIL]
              </li>
            </ul>
          </section>

          <section className="space-y-4">
            <h2 className="font-display text-xl font-semibold">
              6. Intellectual Property
            </h2>
            <p className="text-sm text-muted-foreground leading-loose">
              All content, features, and functionality of the Service —
              including but not limited to text, graphics, logos, software, and
              design — are owned by [COMPANY NAME] and are protected by
              applicable intellectual property laws. The analysis reports
              generated for you are provided for your personal, non-commercial
              use. You may share your own reports but may not represent
              AI-generated analyses as professional medical or genetic advice.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="font-display text-xl font-semibold">
              7. Limitation of Liability
            </h2>
            <p className="text-sm text-muted-foreground leading-loose">
              TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, [COMPANY NAME]
              AND ITS OFFICERS, DIRECTORS, EMPLOYEES, AND AGENTS SHALL NOT BE
              LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR
              PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS OR REVENUES, WHETHER
              INCURRED DIRECTLY OR INDIRECTLY, OR ANY LOSS OF DATA, USE,
              GOODWILL, OR OTHER INTANGIBLE LOSSES, RESULTING FROM:
            </p>
            <ul className="list-disc list-inside text-sm text-muted-foreground space-y-1 ml-4 leading-loose">
              <li>Your use or inability to use the Service</li>
              <li>
                Any decisions made based on analysis results or information
                provided by the Service
              </li>
              <li>
                Errors, inaccuracies, or omissions in AI-generated content
              </li>
              <li>
                Unauthorized access to or alteration of your data or
                transmissions
              </li>
              <li>Any third-party conduct on the Service</li>
            </ul>
          </section>

          <section className="space-y-4">
            <h2 className="font-display text-xl font-semibold">8. Indemnification</h2>
            <p className="text-sm text-muted-foreground leading-loose">
              You agree to indemnify, defend, and hold harmless [COMPANY NAME]
              and its affiliates from and against any claims, liabilities,
              damages, losses, and expenses (including reasonable attorneys&apos;
              fees) arising out of or in any way connected with your access to
              or use of the Service, your violation of these Terms, or your
              violation of any third-party rights (including intellectual
              property or privacy rights).
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="font-display text-xl font-semibold">
              9. Dispute Resolution and Arbitration
            </h2>
            <p className="text-sm text-muted-foreground leading-loose">
              Any dispute arising from or relating to these Terms or the Service
              shall be resolved through binding arbitration in accordance with
              the rules of the American Arbitration Association. Arbitration
              shall take place in [COMPANY ADDRESS jurisdiction]. You agree to
              waive any right to a jury trial or to participate in a class
              action lawsuit.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="font-display text-xl font-semibold">10. Termination</h2>
            <p className="text-sm text-muted-foreground leading-loose">
              We reserve the right to suspend or terminate your access to the
              Service at any time, with or without cause, and with or without
              notice. Upon termination, your right to use the Service will
              immediately cease. Sections regarding Limitation of Liability,
              Indemnification, and Dispute Resolution shall survive termination.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="font-display text-xl font-semibold">11. Changes to Terms</h2>
            <p className="text-sm text-muted-foreground leading-loose">
              We may update these Terms from time to time. We will notify you of
              material changes by posting the updated Terms on this page and
              updating the &quot;Last updated&quot; date. Your continued use of
              the Service after changes constitutes acceptance of the revised
              Terms.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="font-display text-xl font-semibold">12. Contact</h2>
            <p className="text-sm text-muted-foreground leading-loose">
              If you have any questions about these Terms, please contact us at:
            </p>
            <div className="text-sm text-muted-foreground">
              <p>[COMPANY NAME]</p>
              <p>[COMPANY ADDRESS]</p>
              <p>[CONTACT EMAIL]</p>
            </div>
          </section>
        </div>
      </div>
    </div>
  );
}
