"use client";

import {
  Card,
  CardContent,
  CardHeader,
} from "@/components/ui/card";
import { ConfidenceMeter } from "./ConfidenceMeter";
import { SnpTable } from "./SnpTable";
import { PrintReportButton } from "./PrintReportButton";
import { Beaker, Dna, BookOpen, ShieldCheck } from "lucide-react";
import type { AnalysisResult } from "@/lib/types";
import Link from "next/link";

interface ResultsCardProps {
  result: AnalysisResult;
  reportId?: string | null;
  onNewAnalysis: () => void;
}

export function ResultsCard({ result, reportId, onNewAnalysis }: ResultsCardProps) {
  const snpsFound = result.snpMatches.length;
  const sourcesCount = result.sources.length;

  return (
    <div className="space-y-6">
      {/* Print-only branded header */}
      <div data-print-header className="hidden">
        <span className="print-logo">DNA Trait Analyzer</span>
        <span className="print-date">
          Generated {new Date().toLocaleDateString()}
        </span>
      </div>

      <Card>
        <CardHeader>
          <div className="flex items-start justify-between">
            <div>
              <h2 className="font-display font-bold text-2xl capitalize">
                {result.trait}
              </h2>
              <p className="text-sm text-muted-foreground mt-1">
                {result.summary}
              </p>
            </div>
            <PrintReportButton />
          </div>
        </CardHeader>
        <CardContent className="space-y-6">
          {/* Hero stat row */}
          <div className="grid grid-cols-3 gap-4 py-4 border-y border-border">
            <div className="text-center">
              <div className="font-display font-bold text-3xl text-primary">
                {result.confidence}%
              </div>
              <div className="text-xs text-muted-foreground mt-1">
                Confidence
              </div>
            </div>
            <div className="text-center">
              <div className="font-display font-bold text-3xl">
                {snpsFound}
              </div>
              <div className="text-xs text-muted-foreground mt-1">
                SNPs Found
              </div>
            </div>
            <div className="text-center">
              <div className="font-display font-bold text-3xl">
                {sourcesCount}
              </div>
              <div className="text-xs text-muted-foreground mt-1">
                Sources
              </div>
            </div>
          </div>

          <ConfidenceMeter confidence={result.confidence} />

          {/* Genetic Profile section */}
          <div className="border-t border-border pt-6">
            <h3 className="flex items-center gap-2 font-semibold mb-3">
              <Dna className="h-4 w-4 text-primary" />
              Your Genetic Profile
            </h3>
            <SnpTable matches={result.snpMatches} />
          </div>

          {/* Detailed Analysis section */}
          <div className="border-t border-border pt-6">
            <h3 className="flex items-center gap-2 font-semibold mb-3">
              <Beaker className="h-4 w-4 text-primary" />
              Detailed Analysis
            </h3>
            <div className="text-sm text-muted-foreground leading-relaxed whitespace-pre-line">
              {result.interpretation}
            </div>
          </div>

          {/* Research Sources section */}
          {result.sources.length > 0 && (
            <div className="border-t border-border pt-6">
              <h3 className="flex items-center gap-2 font-semibold mb-3">
                <BookOpen className="h-4 w-4 text-primary" />
                Research Sources
              </h3>
              <ul className="text-sm text-muted-foreground space-y-1">
                {result.sources.map((source, i) => (
                  <li key={i} className="flex items-start gap-2">
                    <span className="text-muted-foreground/50 select-none">
                      &bull;
                    </span>
                    {source}
                  </li>
                ))}
              </ul>
            </div>
          )}

          {/* Disclaimer strip */}
          <div className="rounded-lg bg-primary/5 border border-primary/10 p-4">
            <div className="flex items-start gap-3">
              <ShieldCheck className="h-5 w-5 text-primary shrink-0 mt-0.5" />
              <div className="text-xs text-muted-foreground">
                <p className="font-medium mb-1 text-foreground">
                  For Educational Purposes Only
                </p>
                <p>{result.disclaimer}</p>
                <p className="mt-2">
                  This analysis was generated by AI (Anthropic Claude) and may
                  contain errors, inaccuracies, or misinterpretations of
                  scientific literature. AI-generated content should not be used
                  as a basis for medical decisions. Genetic traits are influenced
                  by many factors including gene-gene interactions, epigenetics,
                  and environment — this analysis does not capture the full
                  picture. Always consult a qualified healthcare professional or
                  genetic counselor for medical advice.
                </p>
              </div>
            </div>
          </div>
        </CardContent>
      </Card>

      <div className="text-center space-x-4 print:hidden">
        <button
          onClick={onNewAnalysis}
          className="text-sm text-primary hover:underline"
        >
          Analyze another trait
        </button>
        {reportId && (
          <Link
            href={`/reports/${reportId}`}
            className="text-sm text-primary hover:underline"
          >
            View saved report
          </Link>
        )}
      </div>

      {/* Print-only branded footer */}
      <div data-print-footer className="hidden">
        DNA Trait Analyzer &mdash; AI-powered genetic trait analysis &mdash; For educational purposes only
      </div>
    </div>
  );
}
