"use client";

import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { ConfidenceMeter } from "./ConfidenceMeter";
import { SnpTable } from "./SnpTable";
import { PrintReportButton } from "./PrintReportButton";
import type { AnalysisResult } from "@/lib/types";
import Link from "next/link";

interface ResultsCardProps {
  result: AnalysisResult;
  reportId?: string | null;
  onNewAnalysis: () => void;
}

export function ResultsCard({ result, reportId, onNewAnalysis }: ResultsCardProps) {
  return (
    <div className="space-y-6">
      {/* Print-only branded header */}
      <div data-print-header className="hidden">
        <span className="print-logo">DNA Trait Analyzer</span>
        <span className="print-date">
          Generated {new Date().toLocaleDateString()}
        </span>
      </div>

      <Card>
        <CardHeader>
          <div className="flex items-center justify-between">
            <CardTitle className="capitalize">{result.trait}</CardTitle>
            <PrintReportButton />
          </div>
          <CardDescription>{result.summary}</CardDescription>
        </CardHeader>
        <CardContent className="space-y-6">
          <ConfidenceMeter confidence={result.confidence} />

          <div>
            <h3 className="font-semibold mb-2">Your Genetic Profile</h3>
            <SnpTable matches={result.snpMatches} />
          </div>

          <div>
            <h3 className="font-semibold mb-2">Detailed Analysis</h3>
            <div className="text-sm text-muted-foreground leading-relaxed whitespace-pre-line">
              {result.interpretation}
            </div>
          </div>

          {result.sources.length > 0 && (
            <div>
              <h3 className="font-semibold mb-2">Research Sources</h3>
              <ul className="text-sm text-muted-foreground space-y-1">
                {result.sources.map((source, i) => (
                  <li key={i} className="flex items-start gap-2">
                    <span className="text-muted-foreground/50 select-none">
                      &bull;
                    </span>
                    {source}
                  </li>
                ))}
              </ul>
            </div>
          )}

          <Alert>
            <AlertDescription className="text-xs">
              <p className="font-medium mb-1">
                Important: For Educational Purposes Only
              </p>
              <p>{result.disclaimer}</p>
              <p className="mt-2">
                This analysis was generated by AI (Anthropic Claude) and may
                contain errors, inaccuracies, or misinterpretations of
                scientific literature. AI-generated content should not be used
                as a basis for medical decisions. Genetic traits are influenced
                by many factors including gene-gene interactions, epigenetics,
                and environment — this analysis does not capture the full
                picture. Always consult a qualified healthcare professional or
                genetic counselor for medical advice.
              </p>
            </AlertDescription>
          </Alert>
        </CardContent>
      </Card>

      <div className="text-center space-x-4 print:hidden">
        <button
          onClick={onNewAnalysis}
          className="text-sm text-primary hover:underline"
        >
          Analyze another trait
        </button>
        {reportId && (
          <Link
            href={`/reports/${reportId}`}
            className="text-sm text-primary hover:underline"
          >
            View saved report
          </Link>
        )}
      </div>

      {/* Print-only branded footer */}
      <div data-print-footer className="hidden">
        DNA Trait Analyzer &mdash; AI-powered genetic trait analysis &mdash; For educational purposes only
      </div>
    </div>
  );
}
